name: CI

# Disparadores: este workflow se ejecutar치 en push y pull request a la rama main
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Corre el job en un contenedor con Ubuntu

    steps:
    # 1. Configuraci칩n del entorno
    - name: Checkout code
      uses: actions/checkout@v2
      # Se clona el c칩digo del repositorio en el entorno de CI
    
    # 2. Configurar Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Especifica la versi칩n de Node.js que deseas usar

    # 3. Instalar Dependencias
    - name: Install dependencies
      run: npm install
      # Instala todas las dependencias definidas en package.json

    # 4. Correr los tests
    - name: Run tests
      run: npm test
      # Se ejecutan los tests definidos en el script de package.json ("test": "jest")

    # 5. Generar reporte de coverage (opcional)
    # Si usas coverage con Jest, agrega estos pasos adicionales
    # - name: Generate coverage report
    #   run: npm run coverage
    #   # Genera un reporte de cobertura si es necesario
