name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 17.x, 20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Verify Node.js version
      run: node -v

    - name: ESLint for Node.js 17.x and newer
      if: startsWith(matrix.node-version, '17') || startsWith(matrix.node-version, '20')
      run: npm run lint

    - name: Skip ESLint for older Node.js versions (16.x)
      if: startsWith(matrix.node-version, '16')
      run: echo "Skipping ESLint for Node.js 16.x"

    - name: Run tests
      run: npx mocha
